<?php

namespace Shortcake_Bakery\Shortcodes;

class PDF extends Shortcode {

	public static function get_shortcode_ui_args() {
		return array(
			'label'          => esc_html__( 'PDF', 'shortcake-bakery' ),
			'listItemImage'  => 'dashicons-media-document',
			'attrs'          => array(
				array(
					'label'       => esc_html__( 'Select or upload PDF', 'shortcake-bakery' ),
					'attr'        => 'attachment',
					'type'        => 'attachment',
					'libraryType' => 'application/pdf',
				),
				array(
					'label'       => esc_html__( '...or embed from URL', 'shortcake-bakery' ),
					'attr'        => 'url',
					'type'        => 'text',
				),
			),
		);
	}

	/**
	 * Attach filters and actions for this shortcode
	 *
	 */
	public static function setup_actions() {
		add_filter( 'media_send_to_editor', array( get_called_class(), 'filter_media_send_to_editor' ), 10, 2 );
		add_filter( 'post_mime_types', array( $this, 'filter_post_mime_types' ) );
	}

	/**
	 * Filters the markup sent to the editor if a PDF is added directly through
	 * the media manager; replace it with this shortcode.
	 *
	 * @param string $html Markup generated by media_uplaod_form_handler()
	 * @param int $attachment_id Post ID of attachment being sent to editor
	 */
	public function filter_media_send_to_editor( $html, $attachment_id ) {
		if ( 'application/pdf' !== get_post_mime_type( $attachment_id ) ) {
			return $html;
		}

		return '[' . self::get_shortcode_tag() . ' attachment="' . esc_attr( $attachment_id ) . '" /]';
	}

	/**
	 * Adds "PDF Documents" to the mime-type filters in the media library.
	 *
	 * Allows the PDF shortcode UI to select only .pdf documents to select between.
	 */
	public function filter_post_mime_types( $post_mime_types ) {

		if ( ! isset( $post_mime_types['application/pdf'] ) ) {
			$post_mime_types['application/pdf'] = array(
				__( 'PDF documents', 'shortcake-bakery' ),
				__( 'Manage PDFs', 'shortcake-bakery' ),
				_n_noop( 'PDF <span class="count">(%s)</span>', 'PDF <span class="count">(%s)</span>', 'shortcake-bakery' ),
			);
		}

		return $post_mime_types;
	}

	public static function callback( $attrs, $content = '' ) {

		if ( ! empty( $attrs['attachment'] ) && 'application/pdf' === get_post_mime_type( absint( $attrs['attachment'] ) ) ) {
			$url = get_attached_file( absint( $attrs['attachment'] ) );
		} elseif ( ! empty( $attrs['url'] ) ) {
			$url = esc_url_raw( $attrs['url'] );
		} else {
			return '';
		}

		$url_for_parse = ( 0 === strpos( $url, '//' ) ) ? 'http:' . $url :  $url;
		$scheme = self::parse_url( $url_for_parse, PHP_URL_SCHEME );

		$ext = pathinfo( $url, PATHINFO_EXTENSION );
		if ( 'pdf' !== strtolower( $ext ) ) {
			return '';
		}

		$viewer_url = SHORTCAKE_BAKERY_URL_ROOT . 'assets/lib/pdfjs/web/viewer.html';
		$source = add_query_arg( 'file', rawurlencode( $url ), $viewer_url );

		return '<iframe class="shortcake-bakery-responsive" data-true-height="800px" data-true-width="600px" width="600px" height="800px" frameBorder="0" src="' . esc_url( $source ) . '"></iframe>';
	}

}
